Update config.yml

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,4 +1,5 @@
 # Use the latest 2.1 version of CircleCI pipeline process engine.
+# See: https://circleci.com/docs/configuration-reference
 version: 2.1
 
 # Define jobs to be invoked later in a workflow.
@@ -12,13 +13,16 @@ jobs:
   sonarqube:
     docker:
       - image: sonarsource/sonar-scanner-cli:latest
-    resource_class: small  # Correctly placed at the job level
+    resource_class: small # <-- Move this out of the docker section
     steps:
       - checkout
       - run: |
+          # Set the branch name and output the Sonar branch/org values for debugging
           SONAR_BRANCH="${CIRCLE_BRANCH:-master}"
           echo "Sonar branch value is: $SONAR_BRANCH"
           echo "Sonar org value is: $SONAR_ORG"
+          
+          # Run sonar-scanner with additional error handling and logging
           sonar-scanner \
             -Dsonar.projectKey="$SONAR_PROJECT_KEY" \
             -Dsonar.organization="$SONAR_ORG" \
@@ -26,7 +30,7 @@ jobs:
             -Dsonar.exclusions="**/android/**,**/ios/**" \
             -Dsonar.login="$SONAR_TOKEN" \
             -Dsonar.branch.name="$SONAR_BRANCH" \
-            -Dsonar.sources="."
+            -Dsonar.sources="." || { echo "SonarQube scanner failed"; exit 1; }
 
   newmantest:
     docker:
